GET http://localhost:5000

###

GET http://localhost:5000/usuarios

###

GET http://localhost:5000/usuarios/1

###

POST http://localhost:5000/usuarios
content-type: application/json

{
    "nome": "karam",
    "email": "readit@email.com",
    "senha": "salgado"
}

###

POST http://localhost:5000/usuarios/login
content-type: application/json

{
    "email": "filmeDoPele@email.com",
    "senha": "hexacampeao"
}

###

PUT http://localhost:5000/usuarios?id=4
content-type: application/json

{
    "nome": "Brasil",
    "email": "filmeDoPele@email.com",
    "senha": "hexacampeao"
}

###

DELETE http://localhost:5000/usuarios?id=1